eventmap/accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('settings/', views.profileSettings, name='settings'),
    path('profile/', views.profilePage, name='profile'),
    path('profiles_all/', views.ProfilesAll.as_view(), name='profiles_all'),
    path('detail/<int:pk>', views.user_detail_view, name='detail'),
    path('following', views.followingList, name='following'),
]

eventmap/eventmap/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('events.urls', namespace='events')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventmap/events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    # path('', views.event_list, name='index'),
    path('', views.EventList.as_view(), name='index'),
    path('create_event/', views.create_event, name='create_event'),
    path('edit_event/<int:event_id>', views.edit_event, name='edit_event'),
    path('delete_event/<int:event_id>', views.delete_event, name='delete_event'),
    path('json', views.json, name='json'),
]

eventmap/events/models.py
from django.db import models
from django.contrib.auth.models import User


class Event(models.Model):
    TYPE_OF_EVENT = [
        ('o', 'Остальные'),
        ('s', 'Спорт'),
        ('c', 'Культура'),
        ('e', 'Образование'),
    ]

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=140)
    text = models.TextField()
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    event_date = models.DateTimeField('date event', auto_now=False)
    location = models.CharField(max_length=140)
    location_lat = models.FloatField()
    location_long = models.FloatField()
    type_of_event = models.CharField(max_length=1, choices=TYPE_OF_EVENT, default='o')

    class Meta:
        verbose_name_plural = 'events'

    def __str__(self):
        return f'<{self.title}:{self.user}>'

eventmap/events/views.py
from django.contrib.auth.decorators import login_required
from django.core.serializers import serialize
from django.shortcuts import render, redirect
from django.http import JsonResponse, HttpResponse
from django.views.generic import ListView
from django.db.models import Q

from .models import Event
from .form import CreateEventForm


# def event_list(request):
#     events_all = Event.objects.all().filter(event_date__gte=datetime.date.today()).order_by('event_date')
#     context = {'events_all': events_all}
#     return render(request, 'events/index.html', context)


class EventList(ListView):
    model = Event
    template_name = 'events/index.html'
    context_object_name = 'events_all'

    def get_queryset(self):
        search_query = self.request.GET.get('search', '')

        if search_query:
            return Event.objects.filter(
                Q(title__icontains=search_query) |
                Q(text__icontains=search_query) |
                Q(event_date__icontains=search_query) |
                Q(location__icontains=search_query) |
                Q(type_of_event__icontains=search_query)
            )
        return Event.objects.all()


@login_required(login_url='events:index')
def create_event(request):
    if request.method != 'POST':
        form = CreateEventForm()
    else:
        form = CreateEventForm(data=request.POST)
        if form.is_valid():
            new_event = form.save(commit=False)
            new_event.user = request.user
            new_event.save()
            return redirect('accounts:profile')

    context = {'form': form}
    return render(request, 'events/create_event.html', context)


@login_required(login_url='events:index')
def edit_event(request, event_id):
    event = Event.objects.get(id=event_id)
    if request.method != 'POST':
        form = CreateEventForm(instance=event)
    else:
        form = CreateEventForm(instance=event, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:profile')

    context = {'event': event, 'form': form}
    return render(request, 'events/edit_event.html', context)


@login_required(login_url='events:index')
def delete_event(request, event_id):
    event = Event.objects.get(id=event_id)
    event.delete()
    return redirect('accounts:profile')


def json(request):
    data = Event.objects.all()
    data_1 = serialize('json', data, fields=('title', 'text', 'location', 'location_lat', 'location_long'))
    return HttpResponse(data_1, content_type='application/json')

eventmap/events/templates/events/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

eventmap/events/templates/events/create_event.html
{% extends 'events/base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Создать событие
{% endblock %}

{% block content%}

<link rel="stylesheet" type="text/css" href="{% static 'css/event.css' %}">
<!-- Datepicker -->
<link rel="stylesheet" type="text/css" href="{% static 'build/jquery.datetimepicker.min.css' %}" >
<script src="{% static 'build//jquery.js' %}"></script>
<script src="{% static 'build/jquery.datetimepicker.full.min.js' %}"></script>

<!--
    Укажите свой API-ключ. Тестовый ключ НЕ БУДЕТ работать на других сайтах.
    Получить ключ можно в Кабинете разработчика: https://developer.tech.yandex.ru/keys/
-->
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=3fff23c9-c301-4e68-b14d-aec34f227a40" type="text/javascript"></script>
<script src="event_reverse_geocode.js" type="text/javascript"></script>
<script src="{% static 'js/map.js' %}" type="text/javascript"></script>

<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <form action="{% url 'events:create_event'%}" method="post">
            {% csrf_token %}

             {{ form|crispy }}

             <div class="mt-2">
                <div id="map" style="width: 600; height: 400px"></div>
             </div>

            <button class="btn btn-primary mt-2" name="submit">Создать событие</button>
        </form>
    </div>
</div>

<script>
jQuery.datetimepicker.setLocale('ru');
jQuery('#id_event_date').datetimepicker({
    format:'d.m.Y H:i',
    todayHighlight:'TRUE',
    minDate:new Date(),
});
</script>

{% endblock %}

eventmap/events/templates/events/edit_event.html
{% extends 'events/base.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Создать событие
{% endblock %}

{% block content%}

<link rel="stylesheet" type="text/css" href="{% static 'css/event.css' %}">

<link rel="stylesheet" type="text/css" href="{% static 'build/jquery.datetimepicker.min.css' %}" >
<script src="{% static 'build//jquery.js' %}"></script>
<script src="{% static 'build/jquery.datetimepicker.full.min.js' %}"></script>
<script src="https://api-maps.yandex.ru/2.1/?lang=ru_RU&amp;apikey=3fff23c9-c301-4e68-b14d-aec34f227a40" type="text/javascript"></script>
<script src="event_reverse_geocode.js" type="text/javascript"></script>
<script src="{% static 'js/map.js' %}" type="text/javascript"></script>

<div class="container">
    <div class="d-flex justify-content-center mt-5">
        <form action="{% url 'events:edit_event' event.id%}" method="post">
            {% csrf_token %}

             {{ form|crispy }}

            <div>
                <div id="map" style="width: 600; height: 400px"></div>
            </div>

            <button class="btn btn-primary mt-2" name="submit">Сохранить изменения</button>
        </form>
    </div>
</div>

<script>
jQuery.datetimepicker.setLocale('ru');
jQuery('#id_event_date').datetimepicker({
    format:'d.m.Y H:i',
    todayHighlight:'TRUE',
    minDate:new Date(),
});
</script>

{% endblock %}

eventmap/events/templates/events/index.html
{% extends 'events/base.html' %}
{% load static %}

{% block title %}
Event Map
{% endblock %}

{% block content %}

<!--<script src="{% static 'js/map.js' %}"></script>-->
<script src="https://api-maps.yandex.ru/2.1/?apikey=3fff23c9-c301-4e68-b14d-aec34f227a40&lang=ru_RU" type="text/javascript">
</script>

<script type="text/javascript">
ymaps.ready(init);

function init() {
    var myMap = new ymaps.Map("map", {
            center: [55.76, 37.64],
            zoom: 5,
            controls: ['zoomControl']
        });

    {% for event in events_all %}
    myMap.geoObjects.add(new ymaps.Placemark([{{event.location_lat}}, {{event.location_long}}], {
    hintContent: "{{ event.title }}",
    balloonContentHeader: "{{ event.location }}",
    balloonContent: "{{ event.text }}",
    balloonContentFooter: "<strong>{{ event.event_date|date:'d.m.Y H:i' }}</strong> <strong>{{ event.user.profiles.name }}</strong>"
        }, {
    iconLayout: 'default#image',
    {% if event.type_of_event == 's' %}
    iconImageHref: '{% static 'images/sport.svg'%}',
    iconImageSize: [42, 42],
    iconImageOffset: [-21, -42]
    {% elif event.type_of_event == 'c' %}
    iconImageHref: '{% static 'images/culture.svg'%}',
    iconImageSize: [42, 42],
    iconImageOffset: [-21, -42]
    {% elif event.type_of_event == 'e' %}
    iconImageHref: '{% static 'images/learn.svg'%}',
    iconImageSize: [42, 42],
    iconImageOffset: [-21, -42]
    {% endif %}
    }));
    {% endfor %}
}

</script>

<style>
    .profile-pic{
    width:40px;
    height: 40px;
    border-radius: 50%;
    margin-left: auto;
    margin-right: auto;
    }
</style>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/geo.png' %}" alt="" width="30" height="30 class="
                 d-inline-block align-text-top">
            События твоего города
        </a>

        <form class="d-flex" action="{% url 'events:index' %}" method="get">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>

        <div>
            <form class="container-fluid justify-content-start">
                {% if user.is_authenticated %}
                {% if request.user.profiles.profile_pic %}
                <a href="{% url 'accounts:profile' %}"><img class="profile-pic" src="{{ request.user.profiles.profile_pic.url }}"></a>
                {% else %}
                <a href="{% url 'accounts:profile' %}">{{ request.user.username }}"</a>
                {% endif %}
                <button class="btn btn btn-danger" type="button"><a class="text-light"
                        href="{% url 'accounts:logout' %}">Выйти</a></button>
                {% else %}
                <button class="btn btn btn-primary" type="button"><a class="text-light"
                        href="{% url 'accounts:login' %}">Войти</a></button>
                {% endif %}
            </form>
        </div>
    </div>
</nav>

<div id="map" style="width: 100%; height: 600px"></div>

{% if events_all %}
<ul>
    {% for event in events_all%}
    <div class="card card-body">
    <p><strong>{{ event.title }}</strong></p>
    <p><i>{{ event.text }}</i></p>
    <p>{{ event.location }}</p>
    <p>{{ event.event_date|date:'d.m.Y H:i' }}</p>
    </div>
    {% endfor %}

</ul>
{% else %}
<p>Нет доступных событий</p>
{% endif %}

{% endblock %}