eventmap/accounts/urls.py
from django.urls import path, include

from . import views

app_name = 'accounts'
urlpatterns = [
    path('register/', views.registerPage, name='register'),
    path('login/', views.loginPage, name='login'),
    path('logout/', views.logoutPage, name='logout'),
    path('settings/', views.profileSettings, name='settings'),
    path('profile/', views.profilePage, name='profile'),
    path('profiles_all/', views.ProfilesAll.as_view(), name='profiles_all'),
    path('detail/<int:pk>', views.user_detail_view, name='detail'),
    path('following', views.followingList, name='following'),
]

eventmap/eventmap/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [

    path('admin/', admin.site.urls),
    path('', include('events.urls', namespace='events')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('allauth.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

eventmap/events/urls.py
from django.urls import path

from . import views

app_name = 'events'
urlpatterns = [
    # path('', views.event_list, name='index'),
    path('', views.EventList.as_view(), name='index'),
    path('create_event/', views.create_event, name='create_event'),
    path('edit_event/<int:event_id>', views.edit_event, name='edit_event'),
    path('delete_event/<int:event_id>', views.delete_event, name='delete_event'),
    path('json', views.json, name='json'),
]

eventmap/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class Profiles(models.Model):
    user = models.OneToOneField(User, null=True, blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)
    bio = models.CharField(max_length=200, null=True)
    profile_pic = models.ImageField(default='profile_default.png', null=True, blank=True)
    date_created = models.DateTimeField(auto_now_add=True, null=True)
    following = models.ManyToManyField(User, related_name='following', blank=True)

    def __str__(self):
        return str(self.user.username)

eventmap/accounts/views.py
import datetime

from django.contrib.auth.models import User
from django.views.generic import ListView
from django.contrib import messages
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404

from .form import CreateUserForm, ProfilesForm
from events.models import Event
from .models import Profiles
from itertools import chain


def registerPage(request):
    if request.user.is_authenticated:
        return redirect('events:index')
    else:
        if request.method != 'POST':
            form = CreateUserForm()
        else:
            form = CreateUserForm(data=request.POST)
            if form.is_valid():
                user = form.save()
                login(request, user, backend='django.contrib.auth.backends.ModelBackend')
                return redirect('events:index')

        context = {'form': form}
        return render(request, 'accounts/register.html', context)


def loginPage(request):
    if request.user.is_authenticated:
        return redirect('events:index')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')

            user = authenticate(request, username=username, password=password)

            if user is not None:
                login(request, user)
                return redirect('events:index')
            else:
                messages.info(request, 'Неверные логин или пароль')

        context = {}
        return render(request, 'accounts/login.html', context)


def logoutPage(request):
    logout(request)
    return redirect('events:index')


@login_required(login_url='accounts:login')
def profileSettings(request):
    user = request.user.profiles
    form = ProfilesForm(instance=user)

    if request.method == 'POST':
        form = ProfilesForm(request.POST, request.FILES, instance=user)
        if form.is_valid():
            form.save()

    context = {'form': form}
    return render(request, 'accounts/settings.html', context)


@login_required(login_url='accounts:login')
def profilePage(request):
    events = Event.objects.filter(user=request.user)
    events_now = events.filter(event_date__gte=datetime.date.today()).order_by('event_date')
    name = request.user.profiles.name
    email = request.user.profiles.email
    bio = request.user.profiles.bio
    following = request.user.profiles.following.all()
    following_list = request.user.profiles.following.all()[:3]

    events_following = []
    following_events_sorted = None

    for user in following:
        user = User.objects.get(username=user)
        user_events = Event.objects.filter(user=user).filter(event_date__gte=datetime.date.today())
        events_following.append(user_events)

    following_events_sorted = sorted(chain(*events_following), key=lambda obj: obj.event_date)

    context = {
        'name': name,
        'email': email, 
        'bio': bio, 
        'events_now': events_now,
        'events_following': following_events_sorted,
        'following': following,
        'following_list': following_list,
        }
    return render(request, 'accounts/profile.html', context)


@login_required(login_url='accounts:login')
def followingList(request):
    following = request.user.profiles.following.all()
    context = {'following': following}
    return render(request, 'accounts/following.html', context)


class ProfilesAll(ListView):
    model = Profiles
    template_name = 'accounts/profiles_all.html'
    context_object_name = 'profiles'
    paginate_by = 10

    def get_queryset(self):
        search_query = self.request.GET.get('search', '')

        if search_query:
            return Profiles.objects.filter(name__icontains=search_query).exclude(user=self.request.user)
        return Profiles.objects.all().exclude(user=self.request.user)


def user_detail_view(request, pk):
    user_id = get_object_or_404(User, pk=pk)
    events = Event.objects.filter(user_id=pk)
    user_events = events.filter(event_date__gte=datetime.date.today())
    user_profile = Profiles.objects.get(user_id=pk)
    my_profile = Profiles.objects.get(user_id=request.user)

    if request.method == 'POST':
        if user_profile.user in my_profile.following.all():
            my_profile.following.remove(user_profile.user)
        else:
            my_profile.following.add(user_profile.user)

    if user_profile.user in my_profile.following.all():
        follow = True
    else:
        follow = False

    context = {
        'user': user_id,
        'user_events': user_events,
        'user_profile': user_profile,
        'follow': follow
        }
    return render(request, 'accounts/detail.html', context)

eventmap/accounts/templates/accounts/detail.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static '/css/profile.css' %}" type="text/css">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Профиль пользователя</title>

</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/geo.png' %}" alt="" width="30" height="30 class="
                 d-inline-block align-text-top">
            События твоего города
        </a>
        <div>
            <button class="btn btn-primary" type="button"><a class="text-light"
                                                             href="{% url 'events:create_event' %}">Создать событие</a>
            </button>
        </div>
        <div>
            <button class="btn btn-primary" type="button"><a class="text-light"
                                                             href="{% url 'accounts:profiles_all' %}">Следовать</a>
            </button>
        </div>
        <div>
            <button class="btn btn-primary" type="button"><a class="text-light"
                                                             href="{% url 'events:index' %}">На главную</a></button>
        </div>
    </div>
</nav>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card card-body h-100 border-info">
                {% if user.profiles.profile_pic %}
                <img class="profile-pic" src="{{ user.profiles.profile_pic.url }}">
                {% endif %}
            </div>
        </div>
        <div class="col-md-9">
            <div class="card card-body h-100 border-info">
                <p>{{ user_profile.name }}</p>
                    {% if follow %}
                        <form action="{% url 'accounts:detail' user_profile.user.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{user_profile.user.id}}>
                            <button type="submit" class="btn btn-danger col-md-3">Отписаться</button>
                        </form>
                    {% else %}
                        <form action="{% url 'accounts:detail' user_profile.user.id %}" method="POST">
                            {% csrf_token %}
                            <input type="hidden" name="profile_pk" value={{user_profile.user.id}}>
                            <button type="submit" class="btn btn-primary col-md-3">Подписаться</button>
                        </form>
                    {% endif %}
                <hr>
                <p><b>Контактная информация:</b> {{ user_profile.email }}</p>
                <hr>
                <p><b>О себе:</b> {{ user_profile.bio }}</p>
            </div>
        </div>

    </div>
    <br>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-body" style="text-align: center">Мои события</div>
            {% for event in user_events %}
            <div class="card card-body">

                <p><b>Что: </b>{{ event.title }}</p>
                <p>{{ event.text }}</p>
                <p><b>Где: </b>{{ event.location }}</p>
                <p><b>Когда: </b>{{ event.event_date|date:'d.m.Y H:i' }}</p>
            </div>
            {% endfor %}
        </div>
</body>
</html>

eventmap/accounts/templates/accounts/following.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static '/css/profile.css' %}" type="text/css">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Мои друзья</title>

</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'events:index' %}">
            <img src="{% static 'images/geo.png' %}" alt="" width="30" height="30" class="d-inline-block align-text-top">
            События твоего города
        </a>
        <button class="btn btn-primary" type="button">
          <a class="text-light" href="{% url 'events:index' %}">На главную</a>
        </button>
    </div>
</nav>
<br>
<div class="container d-flex justify-content-center">
    {% for follow in following %}

    <div class="mb-1">
        <div class="card mb-3" style="max-width: 540px;">
            <div class="row g-0">
                <div class="col-md-4">
                    <img src='{{ follow.profiles.profile_pic.url }}' class="profile-pic">
                </div>
                    <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title"><a href="{% url 'accounts:detail' follow.profiles.user_id %}">{{ follow.profiles.name }}</a></h5>
                        <p class="card-text">{{ follow.profiles.bio }}</p>
                    </div>
                </div>
            </div>
        </div>


    {% endfor %}
        </div>
</div>




<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% endif %}
    
    {% for n in page_obj.paginator.page_range %}
      {% if page_obj.number == n %}
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="?page={{ n }}"><span class="sr-only">{{ n }}</span></a>
        </li>
      {% elif n > page_obj.number|add:-3 and n < page_obj.number|add:3 %}
        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>


</body>
</html>

eventmap/accounts/templates/accounts/login.html
<!DOCTYPE html>
{% load socialaccount %}
{% load static %}
<html>

<head>
    <title>Login</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
          integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css"
          integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">


    <style>
		body,
		html {
			margin: 0;
			padding: 0;
			height: 100%;
			background: #e6fff2 !important;
		}
		.user_card {
			width: 350px;
			margin-top: auto;
			margin-bottom: auto;
			background: #74cfbf;
			position: relative;
			display: flex;
			justify-content: center;
			flex-direction: column;
			padding: 10px;
			box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-webkit-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			-moz-box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
			border-radius: 5px;

		}

		.form_container {
			margin-top: 20px;
		}

		#form-title{
			color: #fff;

		}

		.login_btn {
			width: 100%;
			background: #33ccff !important;
			color: white !important;
		}
		.login_btn:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}
		.login_container {
			padding: 0 2rem;
		}
		.input-group-text {
			background: #f7ba5b !important;
			color: white !important;
			border: 0 !important;
			border-radius: 0.25rem 0 0 0.25rem !important;
		}
		.input_user,
		.input_pass:focus {
			box-shadow: none !important;
			outline: 0px !important;
		}

		#messages{
			background-color: grey;
			color: #fff;
			padding: 10px;
			margin-top: 10px;
		}

    </style>

</head>
<body>

<div class="container h-100">

    <div class="d-flex justify-content-center h-100">
        <div class="user_card">
            <div class="d-flex justify-content-center">


                <h3 id="form-title">Вход</h3>
            </div>
            <div class="d-flex justify-content-center form_container">
                <form method="POST" action="">
                    {% csrf_token %}
                    <div class="input-group mb-3">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-user"></i></span>
                        </div>
                        <input type="text" name="username" placeholder="Логин..." class="form-control">
                    </div>
                    <div class="input-group mb-2">
                        <div class="input-group-append">
                            <span class="input-group-text"><i class="fas fa-key"></i></span>
                        </div>
                        <input type="password" name="password" placeholder="Пароль..." class="form-control">
                    </div>

                    <div class="d-flex justify-content-center mt-3 login_container">
                        <input class="btn login_btn" type="submit" value="Войти">
                    </div>
                </form>

            </div>

            {% for message in messages %}
                <p id="messages">{{ message }}</p>
            {% endfor %}

            <div class="mt-4">
                <div class="d-flex justify-content-center links">
                    Нет аккаунта? <a href="{% url 'accounts:register' %}" class="ml-2">Зарегистрироваться</a>
                </div>
				<div class="d-flex justify-content-center links">
                    <p>Или через социальные сети</p>
                </div>
                <div class="d-flex justify-content-center links">
                    <a class="mr-1" href="{% provider_login_url 'vk'%}" target="blank"><img class="social" src="{% static 'images/VK.png' %}" width="50" height="50"></a>
                    <a href="{% provider_login_url 'github' %}"><img class="social" src="{% static 'images/github.png' %}" width="50" height="50"></a>
                </div>
            </div>
        </div>
    </div>
</div>
</body>

</html>

eventmap/accounts/templates/accounts/profile.html
{% load static %}
<html>
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.0/css/all.css"
          integrity="sha384-lZN37f5QGtY3VHgisS14W3ExzMWZxybE1SJSEsQp9S+oqd12jhcu+A56Ebc1zFSJ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/profile.css' %}" type="text/css">
    <title>Профиль пользователя</title>

</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/geo.png' %}" alt="" width="30" height="30 class="
                 d-inline-block align-text-top">
            События твоего города
        </a>
        <div>
            <button class="btn btn-primary" type="button"><a class="text-light"
                                                             href="{% url 'events:create_event' %}">Создать событие</a>
            </button>
        </div>
        <div>
            <button class="btn btn-primary" type="button"><a class="text-light"
                                                             href="{% url 'accounts:profiles_all' %}">Следовать</a>
            </button>
        </div>
        <div>
            <button class="btn btn-primary" type="button"><a class="text-light"
                                                             href="{% url 'events:index' %}">На главную</a></button>
        </div>
    </div>
</nav>
<br>
<div class="container" >
    <div class="row">
        <div class="col-md-3">
            <div class="card card-body h-100 border-info">
                {% if request.user.profiles.profile_pic %}
                <img class="profile-pic" src="{{ request.user.profiles.profile_pic.url }}">
                {% endif %}
                <a href="{% url 'accounts:settings' %}"><button type="button" class="btn btn-warning">
                    <i class="far fa-address-card"></i>
                </button></a>
            </div>
        </div>
        <div class="col-md-6">
            <div class="card card-body h-100 border-info">
                <p>{{ name }}</p>
                <hr>
                <p><b>Контактная информация:</b> {{ email }}</p>
                <hr>
                <p><b>О себе:</b>{{ bio }}</p>
            </div>
        </div>
        <div class="col-md-3">
            <div class="card card-body h-100 border-info" style="text-align: center">
                <p><a href="{% url 'accounts:following' %}">Подписки</a></p>
                {% for follow in following_list %}
                    <p><img class="following-pic" src="{{ follow.profiles.profile_pic.url }}" width="40" height="40"> {{ follow.profiles.name }}</p>
                {% endfor %}
            </div>
        </div>
    </div>
    <br>
    <div class="row">
        <div class="col-md-6">
            <div class="card card-body" style="text-align: center">Мои события</div>
            {% for event in events_now %}
            <div class="card card-body">
                <p><b>Что: </b>{{ event.title }}</p>
                <p><i>{{ event.text }}</i></p>
                <p><b>Где: </b>{{ event.location }}</p>
                <p><b>Когда: </b>{{ event.event_date|date:'d.m.Y H:i' }}</p>
                <p><a href="{% url 'events:edit_event' event.id %}" methods="post">
                    <button class="btn btn-warning">
                        <i class="far fa-edit"></i>
                    </button></a>
                    <a href="{% url 'events:delete_event' event.id%}" methods="post">
                    <button class="btn btn-danger">
                        <i class="far fa-trash-alt"></i>
                    </button></a>
                </p>
            </div>
            {% endfor %}
        </div>
        <div class="col-md-6">
            <div class="card card-body" style="text-align: center">События друзей</div>
                {% for follow in events_following %}
                <div class="card card-body">
                    <p><b>Что: </b>{{ follow.title }}</p>
                    <hr>
                    <p><i>{{ follow.text }}</i></p>
                    <p><b>Где: </b>{{ follow.location }}</p>
                    <p><b>Когда: </b>{{ follow.event_date|date:'d.m.Y H:i' }}</p>
                    <p><b>Создатель: {{ follow.user.profiles.name }}</b></p>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
</body>
</html>

eventmap/accounts/templates/accounts/profiles_all.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static '/css/profile.css' %}" type="text/css">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Профиль пользователя</title>

</head>
<body>
<nav class="navbar navbar-light" style="background-color: #e3f2fd;">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'events:index' %}">
            <img src="{% static 'images/geo.png' %}" alt="" width="30" height="30" class="d-inline-block align-text-top">
            События твоего города
        </a>

        <form class="d-flex" action="{% url 'accounts:profiles_all' %}">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-primary" type="submit">Search</button>
        </form>
        <button class="btn btn-primary" type="button">
          <a class="text-light" href="{% url 'events:index' %}">На главную</a>
        </button>
    </div>
</nav>
<br>
<div class="container d-flex justify-content-center">
{% for profile in profiles %}

<div class="mb-1">
    <div class="card mb-3" style="max-width: 540px;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src='{{ profile.profile_pic.url }}' class="profile-pic">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title"><a href="{% url 'accounts:detail' profile.user_id %}">{{ profile.name }}</a></h5>
                    <p class="card-text">{{ profile.bio }}</p>
                </div>
            </div>
        </div>
    </div>

  {% endfor %}
    </div>
</div>




<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
    {% endif %}
    
    {% for n in page_obj.paginator.page_range %}
      {% if page_obj.number == n %}
        <li class="page-item active" aria-current="page">
          <a class="page-link" href="?page={{ n }}"><span class="sr-only">{{ n }}</span></a>
        </li>
      {% elif n > page_obj.number|add:-3 and n < page_obj.number|add:3 %}
        <li class="page-item"><a class="page-link" href="?page={{ n }}">{{ n }}</a></li>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <li class="page-item">
        <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
    {% endif %}
  </ul>
</nav>


</body>
</html>

eventmap/accounts/templates/accounts/settings.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static '/css/profile.css' %}" type="text/css">
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <title>Настройки пользователя</title>

</head>
<body>
<br>
<div class="container">
    <div class="row">
        <div class="col-md-3">
            <div class="card card-body h-100 border-info">
                {% if request.user.profiles.profile_pic %}
                <img class="profile-pic" src="{{ request.user.profiles.profile_pic.url }}">
                {% endif %}
                <button type="button" class="btn btn-warning"><a class="text-light" href="{% url 'accounts:profile' %}"><h5 style="text-align: center">Вернуться</h5></a></button>
            </div>
        </div>
        <div class="col-md-9">
            <div class="card card-body h-100 border-info">
                <form method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.as_p }}

                <input type="submit" class="btn btn-primary" name="Update Information">
            </form>
            </div>
        </div>
    </div>
    <br>
</div>
</body>
</html>